### ISSUE TITLE
how to use the headless gem

### ISSUE THREAD

**Issue by jjb** [thoughtbot/capybara-webkit#1002]
The docs say "try out the headless gem", but neither the capybara-webkit readme nor the headless readme say how to integrate it into a test suite configuration.

https://github.com/thoughtbot/capybara-webkit#ci

How do I use this? After I get my answer I'll submit a PR and/or wiki page.

Thanks!

**Comment by leonid-shevtsov** [comment]
Hey @jjb, `headless` author here. Did you get it running by now? If not, I can provide some guidance, if so, could you share some specific pain points so I can refine the readme?

**Comment by jjb** [comment]
Hi! Thanks for your response. I've since gone with a different setup, and didn't collect any useful observations when I was experimenting back in May.

**Comment by RemyMaucourt** [comment]
I ran into the same problem recently, and I choose not to use the headless gem because I had no idea how to use it. 

Since that choice I'm struggling with [xvfb and docker-compose](https://github.com/thoughtbot/capybara-webkit/issues/1019). I would appreciate any information about the setup of the gem, so I can give it a try.
