### ISSUE TITLE
JavaScript is not running.

### ISSUE THREAD

**Issue by ChrisCPO** [thoughtbot/capybara-webkit#1051]
I have a rails 5.1 .4, that I created with suspenders 1.45

I have an app with some failing(well pending tests) (brach)[https://github.com/ChrisCPO/music_app/tree/feature/advanced_searching]

see spec/features/search_spec.rb
if you look at the screen shots produced they Ajax /Jquery is not working.

**Comment by jferris** [comment]
That URL is a 404 for me; is `music_app` a private repository?

Can you paste the test, the JavaScript it's testing, and the failure? Screenshots may also be helpful.

If you enable debug mode, you can see more details about what capybara-webkit is doing, which may identify the issue.

I'm going to close this issue, as I don't have enough information to identify a potential bug, but feel free to continue commenting and asking questions.

**Comment by twalpole** [comment]
Most likely this is because you're using more modern JS features than QtWebkit supports (ES5)

**Comment by ChrisCPO** [comment]
@jferris I have made it public.
I can get you some screen shots

**Comment by ChrisCPO** [comment]
This is the results of a form that does uses ajax and jquery. it is simply submitting the form, as normal. 

![screenshot_2018-01-11-17-40-29 494](https://user-images.githubusercontent.com/7773951/34851121-9d767702-f6f6-11e7-941c-af1f950f3301.png)

**Comment by twalpole** [comment]
@ChrisCPO As I guessed, you're using ES6 feature 'let' - https://github.com/ChrisCPO/music_app/blob/develop/app/assets/javascripts/search.js#L2 - and maybe others (I stopped looking when I saw `let` in the 2nd line) which is not supported by any currently released version QtWebkit (which capybara-webkit compiles against).  You either need to stick to maximum ES5 features, or transpile (babel, etc) your JS during asset compilation to be ES5 compatible.  If you enabled debug mode (as suggested by @jferris) or set `raise_javascript_errors` in the driver config - https://github.com/thoughtbot/capybara-webkit#configuration - it should have been immediately clear what the issue was.
