### ISSUE TITLE
Disable JavaScript?

### ISSUE THREAD

**Issue by leifbladt** [thoughtbot/capybara-webkit#107]
I want my run my tests, which define the behavior with disabled JavaScript, also with webkit (and not with rack_test).

So, can I disable JavaScript in capybara-webkit to achieve this?

**Comment by monfresh** [comment]
@jferris Are you saying that when using RackTest via `Capybara.use_default_driver` or not specifying any `Capybara.javascript_driver`, you should be able to simulate JS being disabled in the browser? If so, it's not working for me with capybara-webkit 1.4.1, RSpec 3.1.0, and  Rails 4.1.9.

I'm trying to test a `link_to` that sends a POST request, which should fail if JS is disabled in the browser because it sends a GET request instead. However, the Capybara feature spec passes. Is there a way to test these scenarios with Capybara?

Thanks!

**Comment by jferris** [comment]
@monfresh Capybara's rack-test driver will [look for `data-method` attributes](https://github.com/jnicklas/capybara/blob/master/lib/capybara/rack_test/node.rb#L54) even though it doesn't support JavaScript, but as of version 2 you need to enable a setting to get that behavior.

It may be worth asking on the Capybara mailing list, as this definitely isn't an issue with capybara-webkit. We expect JavaScript to always work when using capybara-webkit.
