### ISSUE TITLE
Failing to build 1.15 on Alpine while 1.14 builds fine

### ISSUE THREAD

**Issue by DannyBen** [thoughtbot/capybara-webkit#1075]
Hello,

I have started getting errors with an older version of Capybara Webkit, so I thought I would upgrade first before seeking help.

Trying to upgrade to 1.15 I am getting a "failed to build native extensions", and installing 1.14.0 builds just fine.

Can you point me in the right direction, as to what changed in 1.15 that probably requires another alpine library that I do not have?

I would have pasted the output, but it is long and seems to not have any useful information other than to "look at the mkmf.log" - which I found only one in this clean system, under the nokogiri gem.

**Comment by twalpole** [comment]
The changes from 1.14.0 to 1.15.1 are shown at https://github.com/thoughtbot/capybara-webkit/compare/v1.14.0...v1.15.1 .  None of those should affect the libraries required for a linux build, and I would guess it's more likely that you've upgraded some library (Qt perhaps) to a non-compatible version and 1.14.0 is only installing because the system has cached your previously built files. You're going to need to look at the build log to see what the actual error is, and the console failure output should tell you what directory to look in for those logs.

**Comment by DannyBen** [comment]
Thank you.
