### ISSUE TITLE
within_frame issue when locating iframe?

### ISSUE THREAD

**Issue by raygunsix** [thoughtbot/capybara-webkit#127]
Hello

Having some good success with capybara-webkit so far (this is a much needed tool!). However, I'm getting an error when using the within_frame method to locate an iframe:

```
And I should see "widget_content" inside "Image url" # features/step_definitions/web_steps.rb:64
  Unable to locate frame.  (Capybara::Driver::Webkit::WebkitInvalidResponseError)
  ./features/step_definitions/web_steps.rb:68:in `/^I should see "([^"]*)" inside "([^"]*)"$/'
  features/add_image_to_input_stream.feature:14:in `And I should see "widget_content" inside "Image url"'
```

And this is my cucumber step definition:

```
When /^I should see "([^"]*)" inside "([^"]*)"$/ do |x, y|
  sleep 5 # sleep while jquery loads iframe
  page.should have_xpath("//iframe[@id='widget_frame']") # matches
  page.should have_css('iframe#widget_frame') # matches
  page.within_frame("widget_frame") # doesn't match
end
```

Any idea why this code doesn't work?

**Comment by Chan-Chan1** [comment]
iframe handling in Cucumber+Selenium Webdriver is working fine in Chrome but not in IE (10). Could anybody suggest solution for handling iframes in IE browser.

**Comment by achikin** [comment]
It turned out that frames have indexes and you can do
```ruby
within_frame(0) do
...
end
```

**Comment by Chan-Chan1** [comment]
But within_frame is not working for me. im using Cucumber(1.3.15) + Selinium webdriver + Page-object (1.0.2). I used
        ifram = @browser.window_handles.last
        @browser.switch_to.window(ifram)
for handling with iframe and its working with Chrome but not with IE (10).
Actually the iframe contains a report like with pagination, the issue is with the screen resolution; the pagination links goes below the browser window. If I try to click the 'next >>' link, in chrome its clicking but not in IE.
IE requires the object to be visible for performing any action on it. but I need to run it on IE also.
Is there any solution for this.
