### ISSUE TITLE
`has_content?` is not matching when it should

### ISSUE THREAD

**Issue by jfelchner** [thoughtbot/capybara-webkit#175]
I currently am getting this error when using `has_content?`.  I'm not sure if this is a capybara-webkit issue or if it's a capybara issue.  I'm posting it here just in case it's the way that the content is being sent to capybara.

Here is my error output:

    expected there to be content "Log in to use your Facebook account with Facebook App Capybara." in
    "\nSign UpFacebook helps you connect and share with the people in your life.\nFacebook Login\n
    Log in to use your Facebook account with Facebook App Capybara.\nEmail:\nPassword:\n\nKeep me logged in\n
    or Sign up for Facebook\nForgot your password?\nEnglish (US)EspañolPortuguês (Brasil)
    Français (France)DeutschItalianoالعربيةहिन्दी中文(简体)日本語…\nFacebook © 2011\nMobile · Find Friends ·
    Badges · People · Pages · About · Advertising · Create a Page · Developers · Careers · Privacy · 
    Terms · Help"

In RSpec, I'm doing this:

    page.should have_content 'Log in to use your Facebook account with Facebook App Capybara.'

Does anyone have any idea why this isn't matching?

**Comment by calleerlandsson** [comment]
Were the other failures also related to `text-transform: uppercase` CSS rules? If so, are you still experiencing these issues in the current version of capybara-webkit?

**Comment by calleerlandsson** [comment]
I'll close this issue due to inactivity. Please re-open it if you're still experiencing these issues.

**Comment by nijotz** [comment]
Here's something that I just experienced that may help others:

I had a `has_content?` test that was passing and then started failing.  I had changed some versions of some testing libraries and thought it may have been that.  Turns out some CSS rules changed so that the content was technically on the page, but wasn't accessible because you couldn't scroll down far enough to see that content.  Window size and scrolling may affect this test.
