### ISSUE TITLE
Forms with :remote => true still requesting html even with :webkit driver

### ISSUE THREAD

**Issue by macmartine** [thoughtbot/capybara-webkit#351]
My form submits just fine when run manually in the browser. But with the webkit driver it requests html instead of js. Here's all the relevant code:

_edit.html.haml

```
=semantic_form_for [:admin, @business], :url => admin_business_path, :remote => true do |f|
 ...
```

gemfile

```
group :test do
  gem 'factory_girl_rails', :require => false
  gem 'timecop'
  gem 'database_cleaner'
  gem 'minitest'
  gem 'capybara', '>= 1.1.2'
  gem 'launchy'
  gem 'turn'
  gem 'guard-minitest'
  gem 'capybara-email'
  gem 'capybara-webkit'
  gem 'capybara_minitest_spec'
end
```

minitest_helper.rb

```
ENV["RAILS_ENV"] = "test"
require File.expand_path("../../config/environment", __FILE__)
require "minitest/autorun"
require "capybara/rails"
require "active_support/testing/setup_and_teardown"
require "factory_girl_rails"
require 'database_cleaner'

class IntegrationTest < MiniTest::Spec
  include Rails.application.routes.url_helpers
  include Capybara::DSL
  include Capybara::Email::DSL
  register_spec_type(/integration$/, self)
  Capybara.javascript_driver = :webkit
end
```

business_integration_test.rb

```
require 'minitest_helper'
require 'ruby-debug'

describe "Business integration" do

  before :each do
    Capybara.javascript_driver = :webkit
    Capybara.current_driver = Capybara.javascript_driver
    @business = Factory.build(:presaved_business)
  end

  def login
    [...]
  end

  describe "Your Business", :js => true do

    it "Should show error if business name is blank" do
      login
      fill_in 'Name', :with => ''
      save_and_open_page
      click_button 'Save'
      save_and_open_page #opens a blank page -- work fine when run manually in browser
      page.must_have_content "can't be blank"
    end
  end
end
```

**Comment by glaszig** [comment]
experiencing the same. using my app in the browser is working but doing the same with capybara the `format` does not appear to be set to `js` and i can see in the log that rails is searching the view to be rendered with `formats: [:html]`.

does not work with neither `:webkit` nor `:poltergeist`.

now, apparently i'm too stupid to get `:webkit_debug` to output anything.

fwiw:
* ruby (2.1.3)
* capybara (2.4.4)
* poltergeist (1.5.1)

**Comment by jferris** [comment]
@glaszig what version of capybara-webkit are you using? Can you show some code from the spec, your log, and the view you're testing? Can you paste the error/output you get when using `:webkit_debug`?

**Comment by type-face** [comment]
Having the same issue. 

capybara 2.5.0
capybara-webkit 1.7.1
minitest-rails-capybara 2.1.1
ruby 2.1.4p265

Here's the test:

    should "step through activate first device sequence", :js => true do
      visit root_path
      fill_in "user_email", :with => @user_no_devices[:email]
      fill_in "user_password", :with => @user_no_devices[:password]
      click_button "SIGN IN"

      fill_in "claim_serial", :with => "xxxx"
      click_button "ACTIVATE"

      page.has_content?("device successfully added.")
      page.has_content?("SETTINGS")

      fill_in "device_description", :with => "claimed device"
      page.find(:fillable_field, "alarm_delay").set(6)
      click_button("next_button")

      page.has_content?("WIFI SET UP")
      find_link("NEXT >>").click

      page.has_content?("MONITORING SERVICES")
      click_link("skip_button")
    end

It never finds the "NEXT >>" link because once the next_button is clicked it should run some javascript which will redirect to another page, but because the form is submitted as an html request, this never happens and the page never loads. Instead, it loads a blank page because there is no view associated with that action. This is my respond to block for the action:

    respond_to do |format|
      format.js { render :nothing => true, :head => :ok } 
    end

This is the webkit_debug output that seems relevant:

	Load started 
	Started request to "http://127.0.0.1:60169/monitored_devices/1009/notification_settings" 
	Received "FindXpath(/html)" 
	"TimeoutCommand" waiting for load to finish 
	Received 500 from "http://127.0.0.1:60169/monitored_devices/1009/notification_settings" 
	Page finished with true 
	Load finished 
	Started "FindXpath(/html)" 
	Finished "FindXpath(/html)" with response "Success(1)" 
	Wrote response true "1" 
	Received "Node.visible" 
	Started "Node.visible" 
	Finished "Node.visible" with response "Success(true)" 
	Wrote response true "true" 
	Received "Node.text" 
	Started "Node.text" 
	Finished "Node.text" with response "Success(Internal Server Error

	ActionController::UnknownFormat
	WEBrick/1.3.1 (Ruby/2.1.4/2014-10-27) at 127.0.0.1:60169)" 
	Wrote response true "Internal Server Error

	ActionController::UnknownFormat
	WEBrick/1.3.1 (Ruby/2.1.4/2014-10-27) at 127.0.0.1:60169" 
	Received "Reset()" 


For the record, this test used to run with javascript but has recently broke.

**Comment by twalpole** [comment]
@type-face  This is usually caused by errors in your JS -- in development mode each of your JS files are served individually so an error in one doesn't prevent the rest from executing, however in test mode they get concatenated together so an error in one of your JS files can/will prevent things like jquery-ujs from being initialized.   Check your javascript console for errors.

**Comment by type-face** [comment]
@twalpole Thanks for the reply. I don't think that's the issue, though. The javascript runs fine on production without any js errors. It's definitely submitting the form as an html request, not a javascript request.

**Comment by type-face** [comment]
Just to add to my scenario above, when I look at the request object within the respond_to method I can see that *action_dispatch.request.accepts* and *action_dispatch_request.formats* is specified in development:


> "action_dispatch.request.accepts"=>   [#Mime::Type:0xa885cd4 @string="text/javascript", @symbol=:js, @synonyms=["application/javascript", "application/x-javascript"],
	     #Mime::Type:0xc954640 @string="application/ecmascript", @symbol=nil, @synonyms=[],
	     #Mime::Type:0xc9545f0 @string="application/x-ecmascript", @symbol=nil, @synonyms=[],
	     #Mime::Type:0xc9545a0 @string="*/*", @symbol=nil, @synonyms=[]],
	   "action_dispatch.request.formats"=>  [#Mime::Type:0xa885cd4 @string="text/javascript", @symbol=:js, @synonyms=["application/javascript", "application/x-javascript"]>,
	     #Mime::Type:0xc954640 @string="application/ecmascript", @symbol=nil, @synonyms=[],
	     #Mime::Type:0xc9545f0 @string="application/x-ecmascript", @symbol=nil, @synonyms=[],
	     #Mime::Type:0xc9545a0 @string="*/*", @symbol=nil, @synonyms=[]]}, 



However, when I run the test with capybara, *action.dispatch.requests.accepts* does not exist and *action.dispatch.request.formats* is set to html:

>   "action_dispatch.request.formats"=> [#Mime::Type:0xb62d364 @string="text/html", @symbol=:html, @synonyms=["application/xhtml+xml"]]},

**Comment by twalpole** [comment]
@type-face  jquery-ujs (assuming your using jQuery) is what makes links with remote: true submit as ajax requests rather than doing a normal html post, so if it isn't initializing properly it will do normal html posts instead of ajax.   Production mode working isn't really a verification that you don't have any JS errors because it (rails default config) runs the JS through uglifier which strips console.log/debugger/etc statements from the file (test mode doesn't by default run uglifier)- so if you had errors in any of those lines it would still work fine in production.  Are you 100% sure that you're not seeing any errors at all in the console in dev mode on the page you're seeing this error on?

**Comment by type-face** [comment]
These are the only two warnings I get in the console for the page:

>mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create d3.v3.min.js:3:100

>Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

Could the getPreventDefault() be causing it?

**Comment by type-face** [comment]
I stand corrected @twalpole. I updated my jquery-rails gem and that seemed to do the trick! Thanks for the help!
