### ISSUE TITLE
Entity bodies are not passed back for DELETE requests

### ISSUE THREAD

**Issue by vrish88** [thoughtbot/capybara-webkit#427]
Our app passes data back in the entity body of a DELETE request via jquery. It works fine in the browser but when capybara-webkit makes the request only the parameters in the url query string are received by the server.

It appears that entity bodies are allowed for DELETE requests by the HTTP 1.1 spec:
http://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

We are using capybara-webkit  0.13.0 and qt 4.8.0.

**Comment by shepmaster** [comment]
> Unfortunately the problem is further up the stack.
> Closing this out, as there's nothing we can do without QtWebKit support.

Unfortunately, the earlier link to the implementation in QtWebKit is now a 404 so I can't check this easily for myself, but is it possible that Qt 5.x would have changed any behavior here?

If I go to http://jquery.com and use the console in Safari, Firefox, or Chrome, I can execute from the console:

```js
$.ajax({url: '/', method: 'DELETE', data: {a: 1}})
```

And I see that the parameter is passed along. So it seems that the major browsers have decided that they will to support this.

**Comment by abhchand** [comment]
For anyone else coming across this, I noticed the same behavior on `PATCH` where the data body was not being passed back to the server on AJAX requests. 

I'm guessing it's because of a similar issue (maybe someone above can confirm), but the solution was to use `PUT` instead. If you're using Rails with a standard `:update` action, it should accept both `PATCH` and `PUT` on plural resources, which you can confirm with `rake routes`
