### ISSUE TITLE
Capybara::Webkit::ClickFailed

### ISSUE THREAD

**Issue by abacha** [thoughtbot/capybara-webkit#494]
I have this spec:

```
  context "updating", js: true do
    background do
      create(:visit_report, owner_id: comercial.id)
      visit "/visit_reports/"
    end

    scenario "failure" do
      find(:xpath, '//*[@id="body"]/table/tbody/tr[1]/td[4]/a[2]').click
      within(".clients") { find('.remove').click }
      click_on "Salvar"
      page.should have_content("Clientes não pode ficar vazio")
    end
  end
```

but when I ran it, it raises an error:

```
     Failure/Error: find('.remove').click
     TypeError:
       exception class/object expected
```

I've tried to debug deeply and found this internal message:

```
"Failed to click element /html/body/div[@id='wrapper']/div[@id='body']/form[@id='edit_visit_report_1']/div[2]/div/div[3]/a at unknown position"
```

if I change the current_driver to :selenium, it works
I'm using capybara-webkit v0.14.1 with capybara v2.0.2

**Comment by redbar0n** [comment]
@aguynamedben Thanks for the info on how to install the latest Qt version. I was scratching my head and thinking I had to install it without my beloved Homebrew.

**Comment by makotoshimoda** [comment]
Hi, I`m having a problem to select a Radio button. Capybara is saying that the same element are overlapping himself.

Capybara::Webkit::ClickFailed: Failed to click element /html/body/div[1]/div[3]/form[@id='form']/div[1]/div[@id='pr']/div/div[1]/label/input[@id='X'] because of overlapping element /html/body/div[1]/div[3]/form[@id='form']/div[1]/div[@id='pr']/div/div[1]/label/input[@id='X'] at position 0, 0; 

I can find the element, but can t click.
Thanks for the help.

**Comment by jferris** [comment]
@makotoshimoda could you open a new issue for your particular problem?

**Comment by narendra-chandratre** [comment]
+1 
@oelmekki - Its working. Thanks for shot and quick solution.!

**Comment by obromios** [comment]
Sufferers might be interested in [this workaround](http://stackoverflow.com/a/36620706/1299362), which is more rails oriented.

As well for those wanting to upgrade to the latest version of qt, here are some [concise instructions](http://stackoverflow.com/a/33643674/1299362).

**Comment by netwire88** [comment]
This post is getting really long. But those who are too lazy to read the entire post, these examples seem to work well:
```
find(:css, 'a.btn.btn-small.toggle_moderator').trigger('click')
```

**Comment by Ethanator** [comment]
I figured out a workaround: temporarily change the conflicting elements to hidden before clicking and change them back to visible after clicking.
For example, I had this function that tries to attach a file to a file input (attach_file is somehow equivalent to clicking). However, when I ran the test with Webkit, the fakeFileInput that I inserted in the window was overlapping with another div somewhere and the attach_file line kept spitting the "Failed to click ... because of the overlapping ..." error. I decided to hide all the other divs before doing attach_file and make them visible again afterwards. It worked perfectly.
``` ruby
def drop_in_dropzone(file_path)
  page.execute_script <<-JS
    var divs = document.getElementsByTagName("div");
    for(var i = 0; i < divs.length; i++){
      divs[i].style.visibility = 'hidden';
    }
    fakeFileInput = window.$('<input/>')
        .append('<style>#fakeFileInput:before{display:inline-block;}</style>')
        .attr({id: 'fakeFileInput', type:'file'})
        .appendTo('body');
  JS
  attach_file 'fakeFileInput', file_path
  page.execute_script <<-JS
    var divs = document.getElementsByTagName("div");
    for(var i = 0; i < divs.length; i++){
      divs[i].style.visibility = 'visible';
    }
    var fileList = [fakeFileInput.get(0).files[0]];
    var e = jQuery.Event('drop', { dataTransfer : { files : fileList } });
    $('.dropzone')[0].dropzone.listeners[0].events.drop(e);
  JS
end
```
