### ISSUE TITLE
Check does not check until the second time

### ISSUE THREAD

**Issue by pignion** [thoughtbot/capybara-webkit#669]
When I use the check method, the checkbox is not checked until I do it a second time:
```
[1] pry(#<Cucumber::Rails::World>)> find(:field, 'Use shipping address').checked?
=> false
[2] pry(#<Cucumber::Rails::World>)> check 'Use shipping address'
=> ""
[3] pry(#<Cucumber::Rails::World>)> find(:field, 'Use shipping address').checked?
=> false
[4] pry(#<Cucumber::Rails::World>)> check 'Use shipping address'
=> ""
[5] pry(#<Cucumber::Rails::World>)> find(:field, 'Use shipping address').checked?
=> true
[6] pry(#<Cucumber::Rails::World>)>
```

This began occurring when upgrading from capybara 2.0.2 to 2.4.0 and latest capybara-webkit 1.3.0

This error does not occur when running with Selenium, which leads me to believe this is an issue with capybara-webkit.

**Comment by chendrix** [comment]
I am seeing this issue in our system as well.

**Comment by chendrix** [comment]
I think we found out what at least our issue is.

We are using a javascript plugin that causes a datepicker to appear when we fill in another field. Then when we go to choose our checkbox, the page needs to regain focus. So the two click solution works because the first click regains focus and the second click performs the actual check.

If after selecting something from the datepicker we add something like `page.all('body').first.click` it also appropriately regains focus and the tests work again.

Funnily enough, this "regain focus" problem does not seem to affect selecting from a drop-down, only check boxes (and maybe radio tags? didn't check explicitly).

**Comment by calleerlandsson** [comment]
Thanks for investigating @chendrix.

I'm not sure there is much we can do without a minimal failing example. What do you say, @mhoran, @jferris?

**Comment by jferris** [comment]
I'm going to close this for now, because it's somewhat stale and we haven't been able to reproduce it. If you can come up with a test case we can use, in a separate repo or in a branch, I can take a look at it.
