### ISSUE TITLE
Customize directory of failed screenshots

### ISSUE THREAD

**Issue by ryanong** [thoughtbot/capybara-webkit#711]
Circle CI allows us to store build artifacts and would love to have a failed screenshots to be put in a custom path if possible thanks!

https://circleci.com/docs/build-artifacts

**Comment by mhoran** [comment]
Hey @ryanong. This sounds like a useful feature. We'd gladly accept a well tested, well factored pull request. Previously, an attempt was made to upload screenshots to S3. Check out the work in #632. That work has since stalled, and a more generic solution sounds like a good idea to me.

Happy to hack on this with you sometime, if you're interested.

**Comment by ryanong** [comment]
@mhoran yea! I would love to do that! Lets talk offline about that!

**Comment by jferris** [comment]
This does sound like a useful feature, and I'd gladly accept a pull request to improve this. I'm going to close this, as I don't plan on addressing it.
