### ISSUE TITLE
Icon fonts don't seem to work

### ISSUE THREAD

**Issue by Intrepidd** [thoughtbot/capybara-webkit#728]
Qt5.4 + OSX Yosemite, using HEAD

When looking at screenshots, icons using icon fonts (icomoon, font-awesome) don't appear.

Is this a known issue ? Is there a workaround ? Thanks !

**Comment by mhoran** [comment]
All fonts are overridden to Arial. This is due to a crash on OS X with Qt 4.8. There are also other deficiencies which require overriding CSS pseudo classes due to crashes. 

Ideally all outstanding crashes are nonexistent in Qt 5.3. However, we still support Qt 4.8. The next major release will drop support for 4.8, at which point we can revisit.

**Comment by Intrepidd** [comment]
Thanks for the fast answer :)

While waiting, Is there any way to monkey-patch in order to avoid this ?

**Comment by Intrepidd** [comment]
Also, wouldn't it be possible to only add this custom stylesheet if the QT version is 4.8 ?

**Comment by jferris** [comment]
> Also, wouldn't it be possible to only add this custom stylesheet if the QT version is 4.8?

That would definitely be possible, and I'd merge a pull request that restores icon fonts for Qt 5 if you're interested in submitting one.

**Comment by mhoran** [comment]
While it's certainly possible to conditually enable icon fonts, this is not something I'd like to do in a point release and without extensive testing for a major release.

Enabling font icons requires removal of `setUserStylesheet` from the `WebPage` constructor.

**Comment by Intrepidd** [comment]
It would probably be a pain to test ...

My issue was to hover on an icon-font element, a bit like what's described in #494 

My temporary ugly-but-working solution : 

```ruby
page.execute_script("$('#selector i.icon-clock').trigger('mouseenter');")
```

**Comment by mhoran** [comment]
@jferris, it looks like all the workarounds were in place just to prevent crashes on OS X in Qt 4.8. I thought there were additional issues, but the commit says otherwise.

I'm hesitant to limit the workaround to Qt version, as layout and behavior could change. That may surprise users who have one version of Qt locally, and another on CI.

@Intrepidd, There are existing tests in `driver_spec.rb`, under the "custom font app" context.

**Comment by Intrepidd** [comment]
@mhoran I mean testing that fonts are overriden in qt 4.8 and not overriden in other qt versions

**Comment by mhoran** [comment]
@Intrepidd, our Travis build matrix targets both Qt 4.8 and 5. Conditionally enabling the override would break the Qt 5 builds, so the related tests would need to be disabled for those builds. On the flip side, you would need to assert custom fonts are enabled only on Qt 5.

I still have reservations about the conditional override, but I'll let @jferris weigh in.

**Comment by Intrepidd** [comment]
I agree with you that it could surprise many users. 

I have my workaround so it's good enough for me, it's probably best to wait for the next major release.

**Comment by onebree** [comment]
I found this from #494 and am having an issue with clicking on font-awesome icons when javascript is enabled. I am using Capybara 2.4.4, Capybara Webkit 1.3.1, Font Awesome Raisl 4.3.0.0

This is the error I am receiving and I cannot seem to figure out why the test is failing. On my local machine I use Qt 4.8.4 and the tests pass. But on a server I am testing on, it has Qt 4.8.6

```ruby
# spec file
    scenario "delete system holiday", js: true do
      click_link(nil, href: edit_system_holiday_path(@system_holiday.id))
      page.accept_confirm { click_link "Delete" }
      success_messages ["System Holiday successfully deleted"]
      has_no_error_message
      expect(page).to have_css("#system_holidays tbody tr", count: 16)
    end

#error output
Failure/Error: click_link(nil, href: edit_system_holiday_path(@system_holiday.id))
     Capybara::Webkit::ClickFailed:
       Failed to find position for element /html/body/div[@id='main']/div/div[3]/div/div[2]/table[@id='system_holidays']/tbody/tr[17]/td[3]/a
```

When I `puts page.html` the element is clearly there. Here is the haml:
```haml
%td= link_to fa_icon("pencil lg"), edit_system_holiday_path(system_holiday)
```

**Comment by lawso017** [comment]
Been running a very old QT 4.8 for a while now due to these icon issues under QT5. Specifically, links containing FontAwesome icons result in ClickFailed events.

However, CircleCI pushed the issue this weekend; looks like my test images are now using a newer QT that breaks my tests.

I went ahead and added conditional inclusion of the icon stylesheet (excluding the icon CSS from the test environment), which is the best workaround I can think of to keep tests running under capybara-webkit under QT5+.

Good news is that QT5 is a lot faster. But looking forward to the next release and dropping the Arial workaround so I can return to serving a single stylesheet in production :-)

**Comment by runephilosof** [comment]
We could start by making it configurable defaulting to on to preserve behavior.
Then it would be easy to use by those not running QT 4.8 on OS X and it would get some testing.
