### ISSUE TITLE
CSS selector performance

### ISSUE THREAD

**Issue by a-laughlin** [thoughtbot/capybara-webkit#731]
While recently trying to understand query performance with css selectors in Capybara, I looked into the [js source](https://github.com/thoughtbot/capybara-webkit/blob/master/src/capybara.js#L43).  Assuming that's the part of capybara which is searching for elements in the page, the use of querySelectorAll() for all css queries surprises me.

Here's a [quick benchmark](http://jsperf.com/getelementsbyclassname-vs-queryselectorall/131).  In queries for classes, using getElementsByClassName(class) would result in queries that are ~190 times faster than querySelectorAll(class) in chrome, and ~2400 times faster than querySelectorAll(class) in firefox.

That gets me curious.  Why is css querySelectorAll() used for all queries when there are significant performance benefits from using a broader spectrum of native methods?

**Comment by jferris** [comment]
Thanks for digging into this!

> While recently trying to understand query performance with css selectors in Capybara, I looked into the js source.

Just to make sure we're on the same page: this project contains the source for capybara-webkit, which is one of the drivers for Capybara. It uses QtWebKit, which is one of the WebKit ports. It doesn't overlap with Selenium, so its selector engine is very different from Firefox's. Although QtWebKit and Chrome have some common ancestors, they also use different selector engines. That being said, it's likely that you'd find similar results in QtWebKit's selector engine.

> That gets me curious. Why is css querySelectorAll() used for all queries when there are significant performance benefits from using a broader spectrum of native methods?

We implement Ruby methods to support the Capybara API. Some of those methods are backed by C++, and some are implemented in JavaScript. The function you linked to exists to support the [find_css](http://www.rubydoc.info/github/jnicklas/capybara/Capybara/Driver/Base#find_css-instance_method) method in Capybara's driver API.

The `find_css` method accepts arbitrary selectors (not just class names), so we'd need to parse the selector to determine if it looks like a simple class lookup. This would likely be slower than WebKit's implementation which does the same thing. If Capybara had a `find_class_name` method, we could implement it using `getElementsByClassName`. However, I'm guessing that the increased surface area in the API would not be worth the performance gain.

When performing benchmarks, it's important to keep track of how they relate to the big picture. Because Capybara tests are involved in network requests, HTML, CSS, and JavaScript rendering, database lookups, and other heavy performers, the consequences of a few extra selector lookups when clicking on links isn't likely to be consequential. Since the gains would be minimal, the increased complexity in Capybara and all its drivers is probably not worth the speed increase.

However, if there's a patch you can come up with to make the driver (or Capybara) faster without a significant increase in complexity, I'm all for it!

I'm going to close this, because I don't see an action item for the capybara-webkit team here, but feel free to continue commenting if you have further thoughts.

**Comment by twalpole** [comment]
@a-laughlin Its important to remember that benchmarks may not be reflecting the reality of testing.  The speedup you're seeing in that benchmark is because its performing the same query over and over, and the browser is caching the results for the getElementsByClassName case.   The speedup would be much less drastic if the classname you were searching for is different each run, which would more closely match real tests.  In real tests the only times you would be running the exact same query over and over would be while waiting for an asynchronous change in the page, and the waiting takes up way more time than any speedup in element finding.
