### ISSUE TITLE
how to hide detail info?

### ISSUE THREAD

**Issue by st0012** [thoughtbot/capybara-webkit#771]
I am using the `1.5.0` version of capybara-webkit, and I always get messages like these when I run a test:
```
Request to unknown URL: http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light")
To allow requests to URLs from this host:
  page.driver.allow_url("fonts.googleapis.com")
Request to unknown URL: http://connect.facebook.net/en_US/sdk.js
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://connect.facebook.net/en_US/sdk.js")
To allow requests to URLs from this host:
  page.driver.allow_url("connect.facebook.net")
Request to unknown URL: http://tjs.sjs.sinajs.cn/open/api/js/wb.js
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://tjs.sjs.sinajs.cn/open/api/js/wb.js")
To allow requests to URLs from this host:
  page.driver.allow_url("tjs.sjs.sinajs.cn")
Request to unknown URL: http://load.sumome.com/
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://load.sumome.com/")
To allow requests to URLs from this host:
  page.driver.allow_url("load.sumome.com")
Request to unknown URL: http://www.google-analytics.com/analytics.js
To block requests to unknown URLs:
  page.driver.block_unknown_urls
To allow just this URL:
  page.driver.allow_url("http://www.google-analytics.com/analytics.js")
To allow requests to URLs from this host:
  page.driver.allow_url("www.google-analytics.com")
Request to unknown URL: http://timg.sjs.sinajs.cn/t4/appstyle/widget/images/library/base/loading1.gif
To block requests to unknown URLs:
  page.driver.block_unknown_urls
```
So I want to ask that if there are any configuration I can do to avoid this?

**Comment by mhoran** [comment]
The default behavior of capybara-webkit is to warn on remote requests. This was due to users being surprised that their tests were requesting external resources, resulting in slow or unreliable tests.

The best way to silence the warnings is to block unknown URLs as described in the message: `page.driver.block_unknown_urls`. If your application relies on external resources, APIs, etc., you'll need to permit those URLs via `page.drive.allow_url`. If you don't care about warnings, you can silence them via `page.driver.allow_unknown_hosts`.

**Comment by st0012** [comment]
thanks!

**Comment by nritholtz** [comment]
Hey. Just as a heads-up, the method was actually implemented as `page.driver.allow_unknown_urls`. I left a line note in the NEWS.md to update this as well.

**Comment by gregblass** [comment]
Where would that code go? page.driver.allow_unknown_urls ? Can't find any mention anywhere on where to put it...

**Comment by gregblass** [comment]
So I ended up doing this to silence about 40 warnings that popped up in my tests after upgrading to the latest version of capybara-webkit recently (using RSpec):

In rails_helper.rb:

    RSpec.configure do |config|
      config.before :each, :js, type: :feature do |example|
        if example.metadata[:js]
          page.driver.allow_unknown_urls
        end
      end
    end

This was based off of code from one of mhoran's other comments.

That only worked when specifying this github repository explicitly in my gemfile, like:

      gem 'capybara-webkit', git: 'https://github.com/thoughtbot/capybara-webkit.git'

I was getting all of those warnings because the app I'm developing uses subdomains, and I've found that the easiest way to deal with them is to develop using subdomain.lvh.me:3000.

Most of the warnings were that, and there were some complaining about google fonts.

Personally I found this all kind of wonky. Hope this makes it more clear for anyone else running into this issue (it was confusing to me at first), and any insight on this method or if I can improve the speed any other way is welcome!

**Comment by gregblass** [comment]
Here's what I ended up going with:

    config.before :each, :js, type: :feature do |example|
      if example.metadata[:js]
        page.driver.allow_url("*.lvh.me")
        page.driver.block_unknown_urls
      end
    end

This allows any local URL I'm trying to hit with subdomain.lvh.me, but blocks the google font requests.

Hopes this helps someone, and again, open to comments here.

**Comment by st0012** [comment]
Great solution, thanks!

**Comment by jferris** [comment]
@gregblass thanks for working through this and documenting your experience. We're working out a better API (with better documentation) for configuring capybara-webkit, including URL whitelists: https://github.com/thoughtbot/capybara-webkit/pull/756
