### ISSUE TITLE
Testing error page with capybara-webkit

### ISSUE THREAD

**Issue by phuongnd08** [thoughtbot/capybara-webkit#784]
I want to test my site that may return an error page (503). The test is successful with selenium but if I try to load that 503 through Webkit, I'm getting: 

```
capybara-webkit-1.5.1/lib/capybara/webkit/browser.rb:289:in `check': Unable to load URL: https://mysite.com/error-page because of error loading https://mysite.com/error-page: Unknown error (Capybara::Webkit::InvalidResponseError)
```

**Comment by jferris** [comment]
This behavior is intentional. A 500 page generally means that something went wrong in the application, so we've found it's more helpful to immediately fail when encountering an error page, rather than letting the test continue to run.

This makes sense to me as the default behavior, even though it's different than Selenium. However, I'd be interested in a pull request which extends capybara-webkit so that you can configure which error codes you'd like to ignore.
