### ISSUE TITLE
Errno::EMFILE - too many open files

### ISSUE THREAD

**Issue by chamnap** [thoughtbot/capybara-webkit#802]
I faced the problem as this guys mentioned in this thread, https://groups.google.com/forum/#!topic/ruby-capybara/zlyrubg2vCw. I followed what he did, but I go no luck. Here is the backtrace:

> /Users/chamnapchhorn/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open3.rb:83:in `pipe'
/Users/chamnapchhorn/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/open3.rb:83:in `popen3'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit/connection.rb:80:in `open_pipe'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit/connection.rb:73:in `start_server'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit/connection.rb:31:in `initialize'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit/driver.rb:14:in `new'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit/driver.rb:14:in `initialize'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit.rb:15:in `new'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-webkit-1.6.0/lib/capybara/webkit.rb:15:in `block in <top (required)>'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `call'
/Users/chamnapchhorn/.rvm/gems/ruby-2.1.2@leadr/gems/capybara-2.4.4/lib/capybara/session.rb:79:in `driver'

What is the best way to handle this situation?

**Comment by chamnap** [comment]
`poltergeist` and `selenium` driver has `#quit` method, while capybara-webkit doesn't have this method.

**Comment by mhoran** [comment]
Hey @chamnap. Sorry to hear you're having issues. It'd likely be worth trying to take a look at the open file descriptors on your system, to see what's eating them up. You may also want to consider increasing the limit, if possible.

The latest `capybara-webkit` should automatically quit when the parent Ruby process exits. This behavior has always been there, but was buggy in earlier versions. However, recent releases all but ensure the process will quit when its parent dies. We do not expose a `#quit` method as it is unnecessary under normal circumstances.

Do you have a specific test which causes `capybara-webkit` to crash due to open file descriptors, or does this happen randomly? Debugging a specific case will be much easier if we're able to reproduce it.

Could you provide more information about your system? What OS, and Qt version do you have installed? Did you just start seeing this issue after upgrading any part of your system, or `capybara-webkit` itself? `lsof` should be able to provide some input into what file descriptors are open, and may help dig into what is causing `capybara-webkit` to crash.

**Comment by chamnap** [comment]
@mhoran, Thanks for replying. I already increase the limit on my laptop, mac os 10.10.

It doesn't happen randomly. I have many sidekiq jobs to process. It happens after 10 or 20 jobs were successfully processed. Then, I'll restart the sidekiq processes in order to avoid the error. Previously, I used `v1.5.2` of `capybara-webkit` and `qt4`. I already upgraded to `qt5` and `1.6.0`. However, I still face the same problems.

**Comment by chamnap** [comment]
As mentioned here, https://github.com/teampoltergeist/poltergeist#memory-leak. I thought it would be the same as `capybara-webkit` because each worker creates new session. I would like the functionality of `quit` so that it closes that session after it's finished.

**Comment by chamnap** [comment]
I managed to implement #quit on `capybara-webkit/driver` like that guy did:

```ruby
module Capybara::Webkit
  class Driver
    def quit
      `kill #{@browser.instance_variable_get("@connection").instance_variable_get("@pid")}`
    end
  end
end
```

And the problem get solved. No more too many file open exception is raised.

**Comment by mhoran** [comment]
Hey @chamnap. I didn't realize you were using `capybara-webkit` outside of a testing framework. This usage is "unsupported", but of course you can work around the file descriptor leaks as you've found. 

You may also want to investigate calling `Capybara::Webkit::Driver#reset!`, as an alternative to `#quit`. We are always interested in tracking down file descriptor leaks, but we'd rather fix them than work around them with an option like `#quit`.

**Comment by chamnap** [comment]
Yeah, I understand this usage is unsupported. It's the same issue as here, https://github.com/thoughtbot/capybara-webkit/issues/659. `reset!` doesn't work, I already tried it. It's because after a sidekiq worker has finished its job, a webkit-server doesn't quit. We need to kill it manually.
