### ISSUE TITLE
Adding capybara-webkit makes non :js tests fail with database related errors.

### ISSUE THREAD

**Issue by dimascyriaco** [thoughtbot/capybara-webkit#810]
I'm adding capybara-webkit 1.6.0 to my project and it's causing my test to fail on a really strange way.  I'm using the database-cleaner's recommended configuration for capybara, with :js test cleaned with the 'truncation' strategy. But the strangest part is that the :js tests are working fine. It's the normal tests that are failing randomly.

I'm stuck with this error for hours now and have no clue how to solve it. Please help.

Here's a gist with the configuration that might be relevant for this: https://gist.github.com/dimascyriaco/3ce56c68be60e06df38a

**Comment by dimascyriaco** [comment]
Found a weird workaround for a weird problem. Running the test separately works.

```shell
bin/rspec --tag ~js
bin/rspec --tag js
```

**Comment by jferris** [comment]
Since the tests run cleanly if you run the JavaScript and other specs independently, it certainly seems as though the data is leaking between specs.

Here's the configuration we use on all our Capybara projects: https://github.com/thoughtbot/suspenders/blob/master/templates/database_cleaner_rspec.rb

Out of curiosity, if you use the `:truncation` strategy for all specs (not just JavaScript), do the specs pass?
