### ISSUE TITLE
css flex support

### ISSUE THREAD

**Issue by agenteo** [thoughtbot/capybara-webkit#822]
Hi there,

is the latest capybara-webkit supporting css flex? I am having issues finding elements on a login page using flex in my layout.

Thanks!

**Comment by jferris** [comment]
Which CSS properties are supported will depend on the version of Qt you have installed. You can see your versions by running this in a test or spec:

    puts page.driver.versions

I'm not sure which versions of Qt and WebKit support flex, but I think anything recent (Qt 5.x) should work.

If you're on Qt 5 and still having issues, here are some questions that will help me debug your issue:

* What application layer are you using? (Rails?) What versions are you using?
* What versions of RSpec, Capybara, capybara-webkit, and Qt are you using?
* Does the spec pass if you use the Selenium driver instead of capybara-webkit?
* What error message are you getting on your login page?
* What does the markup for your login page look like?
* If you're having issues finding elements, what does `save_and_open_screenshot` show?

**Comment by danschultzer** [comment]
Can confirm that flex works with Qt 5.x.

**Comment by zamith** [comment]
I have the same issue in which flex rules are ignored and as such some elements that shouldn't be overlapping, are. I can see this in the screenshot.

Here's the versions I'm using:

Capybara: 2.7.1
capybara-webkit: 1.11.1
Qt: 5.5.1
WebKit: 538.1
QtWebKit: 5.5.1

I'm also using:

Rails 4.2.5
RSpec 3.1.0

And it does work with selenium. Any idea on how to fix this?

**Comment by jferris** [comment]
@zamith It looks like your versions are all pretty up-to-date, so there may not be anything you can do.

Are you using the `-webkit` prefixes for your flex declarations?

**Comment by zamith** [comment]
I forgot to add `autoprefixer` that fixed it. Thanks.

**Comment by jferris** [comment]
Ah, good to know. Looks like this is well-supported by recent versions, so I'm going to close this.
