### ISSUE TITLE
page.current_path takes time to change

### ISSUE THREAD

**Issue by shepmaster** [thoughtbot/capybara-webkit#836]
After clicking on a link, it takes a few hundred milliseconds for `page.current_path` to update. In one measured case, I saw it take between 300-400 milliseconds.

I'm encountering this as I am trying to migrate from PhantomJS to capybara-webkit, so the behavior is not super exciting :innocent: .

Unfortunately, there's no implicit waiting from Capybara for `current_path` / `current_url`. Am I doing something incorrect? Is there a workaround, or should I insert my own busy-wait?

Thanks for a pretty good tool so far!

```
Capybara-Webkit 1.7.0
Capybara 2.4.4
Ruby 2.2.3p173
Qt 4.8.6
```

**Comment by shepmaster** [comment]
This also applies to `page.response_headers`, for probably the same underlying causes.

**Comment by mhoran** [comment]
If the content on the page is being loaded via JavaScript and pushState is being used, this is to be expected. There are other instances where a page load is not triggered before the subsequent request for `current_url` is received. There are even a few bugs with this logic, so if you can isolate a failing test case, that'd make this a lot easier to debug. 

In either case, I'd recommend asserting that you're on the expected page, by checking the content of the page, before using either of these methods. The recommended Capybara strategy is to assert the user experience -- which rarely involves URL structure or headers. Of course, it's sometimes useful to make these assertions, which is why we've added the features.

**Comment by shepmaster** [comment]
> is being loaded via JavaScript and pushState is being used

This is absolutely the case; it's a normal Rails application with turbolinks enabled.

> by checking the content of the page

Yes, this is normally what we do as well, but it's a fine line here about duplicating test content across mostly-unrelated tests.

However, it's more insidious with some of the requests for the response headers, which we use to test if a CSV file was downloaded, or what filename was suggested, for example. Please let me know if there's a way to test that by looking at content! 

This sounds like everything is working for the gem as expected, so maybe the correct path is to document this somewhere. Any suggestions for that?

**Comment by twalpole** [comment]
@shepmaster if you upgrade to capybara 2.5 it has waiting behavior on has_current_path/have_current_path

**Comment by shepmaster** [comment]
> upgrade to capybara 2.5

@twalpole I see that you added that, so thanks! After our emergency switch from PhantomJS to Capybara-Webkit, upgrading Capybara was the first thing I did. Works like a charm, I just wish there were matchers for the other things (headers, status codes) :wink:

**Comment by mhoran** [comment]
Hey @shepmaster. Glad to hear the updated Capybara is working for you. It would probably make sense to add a note, perhaps a new heading above [Offline Application Cache](https://github.com/thoughtbot/capybara-webkit#offline-application-cache), regarding asynchronicity. PRs welcome!
