### ISSUE TITLE
Accept or Decline Javascript Confirmation

### ISSUE THREAD

**Issue by NickClark** [thoughtbot/capybara-webkit#84]
It would be nice if there was a way to accept or deny confirmation or alert dialogs. For instance, in Rails, the default way to delete something is to hide the action as a JS call behind a link. This method requires the user to also accept a deletion confirmation dialog to actually execute the action.

Currently I have to fallback to selenium for those scenarios. This is done using the following code:

``` ruby
page.driver.browser.switch_to.alert.deny
#or
page.driver.browser.switch_to.alert.accept
```

It's also possible that capybara-webkit does this already, I just couldn't find it documented anywhere and my quick scan through the code didn't reveal such functionality.

**Comment by mcbsys** [comment]
Just came across a "gotcha" with this webkit method after upgrading to Rails 4.2.1:  it silently succeeds even if no confirmation popup is displayed.

Rails 4 requires that the `:confirm` message be created in a `:data` hash in order to display the popup:

http://stackoverflow.com/a/19588187/550712

so my code wasn't working but the tests were succeeding.

Is there a way to get the webkit to fail if no popup is present? For now I've switched back to Selenium, which displays "Selenium::WebDriver::Error::NoAlertPresentError:" if the popup is missing.

**Comment by nritholtz** [comment]
@mcbsys, you might be interested in https://github.com/thoughtbot/capybara-webkit/commit/b411f53cfca1be01cfd26faac16ed2796a621e2e. You can call an `accept_confirm` with a block for the action that should prompt the confirmation window.

If the confirmation window doesn't appear, it raises a `Capybara::ModalNotFound`.

**Comment by mcbsys** [comment]
@nritholtz Awesome, thanks very much for that tip!

**Comment by nritholtz** [comment]
No problem. For future reference, all methods related to modal dialogs are documented in Capybara's [README](https://github.com/jnicklas/capybara#modals).

**Comment by TeTiRoss** [comment]
Thank you!
