### ISSUE TITLE
Support for WebAudio

### ISSUE THREAD

**Issue by pedantic-git** [thoughtbot/capybara-webkit#887]
Apologies if this has already been covered elsewhere.

I'm writing capybara code for driving an application that uses the WebAudio API. Unfortunately, the WebKit build bundled with capybara-webkit does not have support for this compiled in.

Would it be possible to tweak the makefiles so that WebAudio support is compiled in?

Thanks!

**Comment by mhoran** [comment]
It's likely that the version of WebKit bundled with the version of Qt that you're using does not support the WebAudio API, and there's not much we can do about that. If you're using Qt 5.5, that's likely the case. Unfortunately, Qt 5.6 doesn't work with capybara-webkit, due to removal of APIs on which we depend.

We're working on porting capybara-webkit to Chromium Embedded (CEF), which provides a more recent version of the WebKit (actually, Blink) API. However, this is a work in progress.

**Comment by pedantic-git** [comment]
Thanks for the explanation! I'll star the project and keep an eye on the CEF work.

**Comment by pinya** [comment]
Is WebRTC support  in capybara-webkit  in the same situation, and it will be available only with migration to Chrome Embedded?

**Comment by annulen** [comment]
We are working on revived QtWebKit (see https://github.com/annulen/webkit), it supports WebAudio API (though there may be bugs). It also supports other new web standards, including large part of ES6.

**Comment by jferris** [comment]
@annulen is there anywhere I can read about the effort to revive QtWebKit?

**Comment by annulen** [comment]
@jferris Yes:
https://github.com/annulen/webkit/wiki
http://lists.qt-project.org/pipermail/development/2016-June/026156.html
http://lists.qt-project.org/pipermail/development/2016-June/026282.html

I'm also planning to write blog post soon, and make TP3 release

**Comment by annulen** [comment]
Here is promised blog post: http://qtwebkit.blogspot.com/2016/08/qtwebkit-im-back.html
New release: https://github.com/annulen/webkit/releases/tag/qtwebkit-tp3

**Comment by twalpole** [comment]
Closing as this is a limitation of QtWebkit
