### ISSUE TITLE
Adding js_errors option

### ISSUE THREAD

**Issue by obduk** [thoughtbot/capybara-webkit#925]
Before spending time writing a pull request, please can people confirm if this is a good idea.

Currently Javascript errors get silently swallowed. I currently have this in my rspec code:

```ruby
RSpec.shared_context 'check js errors', js: true do
  after do
    expect(page.driver.error_messages).to eq []
  end
end
```

I was thinking of adding something similar to the js_errors option in [poltergeist](https://github.com/teampoltergeist/poltergeist) where by default it will raise an exception if there are any JS errors, with an option to turn this off.

Do people think this is a good idea?

**Comment by twalpole** [comment]
Just an FYI -- capybara-webkit adds a have_errors matcher so you could write your expectation as 

    expect(page).not_to have_errors

**Comment by obduk** [comment]
@twalpole that is a bit nicer syntax, thanks. Would you agree with the proposed functionality?

**Comment by twalpole** [comment]
@obduk I don't think it's necessary since an after block is so easy to add, and activate/deactivate with test metadata

**Comment by obduk** [comment]
For me it is not the difficulty in adding it, more the fact that it should be on by default, as most people probably don't want JS errors on their pages, and probably don't know they should have to check for errors.

I think it would also make it easier for new people, for example if they are checking for some text on the page that should of been rendered by JS, and it isn't there because of an error, it is clearer why it has failed.

**Comment by twalpole** [comment]
I think you'd be surprised how many people are fine with some js errors occurring

**Comment by jferris** [comment]
We originally had all JavaScript errors print to stderr, but enough people complained about it that we hid it behind an API.

We currently print errors and other information to the debug log (visible if you set `debug` to true in you capybara-webkit config). I've considered adding a log level option instead. If you could put together a pull request that lets users configure the severity of log output, I'd be interested in it. It might even be okay for the default level to include JavaScript errors, since people could then turn them off.

**Comment by jferris** [comment]
I'm going to close this issue, since it isn't a bug in capybara-webkit, but please feel free to continue commenting and asking questions.

**Comment by obduk** [comment]
@jferris fair enough. Will have a think about it
