### ISSUE TITLE
Installing on Windows 8.1

### ISSUE THREAD

**Issue by DidiRaggio** [thoughtbot/capybara-webkit#938]
I managed to install capybara, although I ran into quite a few issues along the way.
this worked for me:

Install qt-v4.8.5 
add qmake path to env variables in system settings (C:\Qt\4.8.5\bin)
run in console: QMAKE=C:\Qt\4.8.5\bin\qmake gem install capybara-webkit

I hope this helps anyone that has been running into similar issues.
I had to use qt -v4.8.5 because -v4.7 didn't recognize windows 8.1 and -v5 didn't work at all

**Comment by DidiRaggio** [comment]
but the webkit_server doesn't seem to work... can anyone give me a hand?

**Comment by jferris** [comment]
> I had to use qt -v4.8.5 because -v4.7 didn't recognize windows 8.1 and -v5 didn't work at all

I would strongly recommend getting Qt 5 installed. I realize it can be a challenge to get 5.x running on some platforms, and unfortunately we can't offer much assistance for platforms we don't use. However, at this point I would recommend using something else (like Selenium) rather than using capybara-webkit with Qt 4.

> but the webkit_server doesn't seem to work... can anyone give me a hand?

Could you provide some details about how it doesn't work? Is there an error message you see? If you run `webkit_server` directly, does it provide any interesting feedback?
